### ISSUE TITLE
Build failed because of package dependency on de.elbosso.tools

### ISSUE THREAD

**Issue by lihuiniu** [elbosso/csrbuilderswinggui#1]
@elbosso Build failed with the following unresolved dependency. Tried three build commands got the same result.
Command 1: mvn clean install -U
Command 2: mvn compile exec:java
Command 3: mvn -U package assembly:single

[ERROR] Failed to execute goal on project csrbuilderswinggui: Could not resolve dependencies for project de.elbosso.tools:csrbuilderswinggui:jar:1.1.0.SNAPSHOT: Failed to collect dependencies at de.elbosso:data:jar:1.2.0: Failed to read artifact descriptor for de.elbosso:data:jar:1.2.0: Could not transfer artifact de.elbosso:data:pom:1.2.0 from/to Boundless Repository (https://repo.boundlessgeo.com/main/): Transfer failed for https://repo.boundlessgeo.com/main/de/elbosso/data/1.2.0/data-1.2.0.pom: Unknown host repo.boundlessgeo.com: nodename nor servname provided, or not known -> [Help 1]

**Comment by elbosso** [comment]
Sorry for the inconvenience - i got ahead of myself and forgot to commit and push the changed pom - should be fixed now, closing the issue
